version: '3.8'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - db
    restart: always
    networks:
      - app-network

  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./docker/phpmyadmin-override.ini:/usr/local/etc/php/conf.d/phpmyadmin-override.ini
      # - ./docker/php.ini:/usr/local/etc/php/php.ini
    
    depends_on:
      - db
    restart: always
    # healthcheck:
    #   test: ["CMD", "php-fpm-healthcheck"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iirs@12345
      MYSQL_DATABASE: isrolms
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
    volumes:
      - /home/ubuntu/sql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
       
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 60s
      timeout: 20s
      retries: 5
    networks:
      - app-network
    ports:
      - "3306:3306"  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: iirs@12345
    ports:
      - "8081:80"
    volumes:
      - ./docker/phpmyadmin-override.ini:/usr/local/etc/php/conf.d/phpmyadmin-override.ini
    depends_on:
      - db
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge


