version: '3.8'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - db
    networks:
      - app-network
      

  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5  

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - /home/ubuntu/sql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  

networks:
  app-network:
    driver: bridge
